version: "3.7"

services:
  lamp-scriptcase9:
    image: aprendendolinux/lamp-scriptcase9
    restart: always
    container_name: lamp-scriptcase9
    volumes:
      - lamp-scriptcase9:/var/www/html
    ports:
      - "80:80"
volumes:
  lamp-scriptcase9:
